### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [ankitufl/Practice#1]
Hi, i am a graphic designer who loves contributing logos to open-source. If you don't already have a logo i could design one free for you.

**Comment by ankitufl** [comment]
I don't have a logo. But I don't want you to work on a logo for me without me paying anything in return. Thanks for the offer. Very kind of you.

**Comment by dee-y** [comment]
Lolz oh no you don't have to... this is my way of contributing to open-source and i enjoy doing it.

**Comment by ankitufl** [comment]
Sounds great. If you design one for me, happy to add to my repo.

**Comment by ankitufl** [comment]
This looks so good. Let me use this :)

**Comment by ankitufl** [comment]
I updated the README.md with your logo - https://github.com/ankitufl/Practice/blob/master/README.md

Thanks!

**Comment by dee-y** [comment]
Great...here you can download the HD versions of logo as well as MIT license from google drive link https://drive.google.com/drive/folders/1cylaK3G4R0FdJTrfsBT--gJ2h0e9Z15F?usp=sharing 

you can contact me if you need further assistance.
